[package]
name = "mskill-protocol"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
sha2.workspace = true
thiserror.workspace = true
serde_yaml = "0.9"
zip = { version = "2.4", default-features = false, features = ["deflate"] }

[dev-dependencies]
serde_json.workspace = true
