-- Deployment-owned OAuth client; public metadata only. / 部署所有的 OAuth 客户端，仅含公开元数据。
-- Apply as a reviewed forward-only D1 migration, not as separate CLI statements. / 作为已评审的只向前 D1 migration 应用，不得逐条执行。
INSERT INTO oauth_clients(client_id,display_name,client_type,token_endpoint_auth_method,sector_identifier,subject_salt_revision,state,created_at,updated_at) VALUES('mskill-web-staging','mskill Workspace (staging)','confidential','private_key_jwt','skills-staging.moesegfault.dev',1,'enabled',unixepoch(),unixepoch());
INSERT INTO oauth_redirect_uris(redirect_uri_id,client_id,redirect_uri,match_mode,created_at) VALUES('01a10b56-ece8-7e96-8bd5-6c718e692154','mskill-web-staging','https://skills-staging.moesegfault.dev/auth/callback','exact',unixepoch());
INSERT INTO oauth_post_logout_redirect_uris(post_logout_redirect_uri_id,client_id,redirect_uri,created_at) VALUES('01a10b56-ece8-7a9c-8d70-6c168a900ef8','mskill-web-staging','https://skills-staging.moesegfault.dev/auth/logout/callback',unixepoch());
INSERT INTO oauth_client_scopes(client_id,scope,granted_at) VALUES('mskill-web-staging','openid',unixepoch());
INSERT INTO oauth_client_scopes(client_id,scope,granted_at) VALUES('mskill-web-staging','profile',unixepoch());
INSERT INTO oauth_client_scopes(client_id,scope,granted_at) VALUES('mskill-web-staging','offline_access',unixepoch());
INSERT INTO oauth_client_keys(client_id,kid,algorithm,public_jwk_json,created_at) VALUES('mskill-web-staging','mskill-web-staging-2026-10','RS256','{"kty":"RSA","n":"oV82Kpf3H567DubmQPAzWvmvUw2n9Wt3bOZo0-FSpFrmsIJL7_4w4byI0G98bygkuEOsxoYlxxtCqeyd1wvNaa_6VjnJRIEvynlbuUc16P4qu5V4_jYCnnkyPHQ8fTxgOhjcrkBGePZHUaWGPQ5AVQmK3BU-sbeUSKsBVmQaNwLWvPk807kgDVxQyrVCyLdYD4CwCm_h1GCTfhbWgMBjarp3KiWoFPuCQC7pI7gGpD40lSGfhjo2GwMqwYfCVqcWv1CnrYCQYN6gcPQQHxKVT8xH8w4IntI6optc0x3DN12IKQsNTNMYxXAP7jK3MUxNdoG9Hoov43m1WkAdPZz9jw","e":"AQAB","kid":"mskill-web-staging-2026-10","alg":"RS256","use":"sig"}',unixepoch());
INSERT INTO security_audit_events(audit_event_id,event_name,occurred_at,observed_at,client_id,outcome,correlation_id,policy_revision,context_json) VALUES('01a10b56-ece8-782e-814e-07643f495795','identity.oauth_client.created',unixepoch(),unixepoch(),'mskill-web-staging','success','01a10b56-ece8-782e-814e-07643f495795',1,json_object('client_id','mskill-web-staging'));
INSERT INTO audit_archive_outbox(audit_event_id,r2_object_key,next_attempt_at) VALUES('01a10b56-ece8-782e-814e-07643f495795',printf('security-audit/unix-day-%d/%s.json',CAST(unixepoch()/86400 AS INTEGER),'01a10b56-ece8-782e-814e-07643f495795'),unixepoch());
