-- Deployment-owned OAuth client; public metadata only. / 部署所有的 OAuth 客户端，仅含公开元数据。
-- Apply as a reviewed forward-only D1 migration, not as separate CLI statements. / 作为已评审的只向前 D1 migration 应用，不得逐条执行。
INSERT INTO oauth_clients(client_id,display_name,client_type,token_endpoint_auth_method,sector_identifier,subject_salt_revision,state,created_at,updated_at) VALUES('mskill-web','mskill Workspace','confidential','private_key_jwt','skills.moesegfault.dev',1,'enabled',unixepoch(),unixepoch());
INSERT INTO oauth_redirect_uris(redirect_uri_id,client_id,redirect_uri,match_mode,created_at) VALUES('01a10b56-ed0d-7b1c-a5fa-ecbe235f7fc4','mskill-web','https://skills.moesegfault.dev/auth/callback','exact',unixepoch());
INSERT INTO oauth_post_logout_redirect_uris(post_logout_redirect_uri_id,client_id,redirect_uri,created_at) VALUES('01a10b56-ed0d-75eb-98b6-f585e9e94d08','mskill-web','https://skills.moesegfault.dev/auth/logout/callback',unixepoch());
INSERT INTO oauth_client_scopes(client_id,scope,granted_at) VALUES('mskill-web','openid',unixepoch());
INSERT INTO oauth_client_scopes(client_id,scope,granted_at) VALUES('mskill-web','profile',unixepoch());
INSERT INTO oauth_client_scopes(client_id,scope,granted_at) VALUES('mskill-web','offline_access',unixepoch());
INSERT INTO oauth_client_keys(client_id,kid,algorithm,public_jwk_json,created_at) VALUES('mskill-web','mskill-web-2026-10','RS256','{"kty":"RSA","n":"kLc2NmF8lUV0aeo3JIHjju8aQobVFWrhp_WlyfI9aQ80u5S8FuBkknVH780H7omFYFnHUm8NgjLXORv1OnBsXVe23IUa4J_0F7Lo0Uf918OPdOmHL6k0ZAjswUHzT1f0vgFOJGtMREW7lvJaT58Jtm6KbAEowAx1__dM7wMVkycn5Zv3uckWTiu3owR58W2iDVyuT9bJhDjn29ljRHNl86lrNTwA2pMFajPO0Gm3SKs2g-yX8jGIZmRuKUDEsQDBKQSF470IeZzMwJBZCLxdy_fPhPYqlrRZTfTpysqxt8Quw-iAVxpR1JNdABbEFKxfWT5rQ2hYVJ_iP88CY7ECSQ","e":"AQAB","kid":"mskill-web-2026-10","alg":"RS256","use":"sig"}',unixepoch());
INSERT INTO security_audit_events(audit_event_id,event_name,occurred_at,observed_at,client_id,outcome,correlation_id,policy_revision,context_json) VALUES('01a10b56-ed0d-76f0-aa86-96aa5f7e4d82','identity.oauth_client.created',unixepoch(),unixepoch(),'mskill-web','success','01a10b56-ed0d-76f0-aa86-96aa5f7e4d82',1,json_object('client_id','mskill-web'));
INSERT INTO audit_archive_outbox(audit_event_id,r2_object_key,next_attempt_at) VALUES('01a10b56-ed0d-76f0-aa86-96aa5f7e4d82',printf('security-audit/unix-day-%d/%s.json',CAST(unixepoch()/86400 AS INTEGER),'01a10b56-ed0d-76f0-aa86-96aa5f7e4d82'),unixepoch());
