//! Server-rendered product pages, distinct from the authenticated Skill workspace.
//!
//! Static assets are generated by `node web/landing/generate.mjs`. Complete HTML
//! and Markdown references remain available to crawlers and agents without JS.

use worker::{Headers, Response, Result};

/// Resolve a product-host route. Staging is never an indexable product duplicate.
pub fn page(path: &str, staging: bool) -> Option<Result<Response>> {
    let (body, content_type, policy) = match path {
        "/" => (
            include_str!("../../../web/landing/zh-CN.html"),
            "text/html; charset=utf-8",
            include_str!("../../../web/landing/csp-zh-CN.txt"),
        ),
        "/ja/" => (
            include_str!("../../../web/landing/ja.html"),
            "text/html; charset=utf-8",
            include_str!("../../../web/landing/csp-ja.txt"),
        ),
        "/en/" => (
            include_str!("../../../web/landing/en.html"),
            "text/html; charset=utf-8",
            include_str!("../../../web/landing/csp-en.txt"),
        ),
        "/assets/landing.css" => (
            include_str!("../../../web/landing/landing.css"),
            "text/css; charset=utf-8",
            POLICY,
        ),
        "/assets/landing.js" => (
            include_str!("../../../web/landing/landing.js"),
            "text/javascript; charset=utf-8",
            POLICY,
        ),
        "/assets/theme.js" => (
            include_str!("../../../web/shared/theme.js"),
            "text/javascript; charset=utf-8",
            POLICY,
        ),
        "/assets/moe.css" => (
            include_str!("../../../web/shared/style-0.1.2.css"),
            "text/css; charset=utf-8",
            POLICY,
        ),
        "/robots.txt" => (
            if staging {
                "User-agent: *\nDisallow: /\n"
            } else {
                include_str!("../../../web/landing/robots.txt")
            },
            "text/plain; charset=utf-8",
            POLICY,
        ),
        "/sitemap.xml" => (
            include_str!("../../../web/landing/sitemap.xml"),
            "application/xml; charset=utf-8",
            POLICY,
        ),
        "/llms.txt" => (
            include_str!("../../../web/landing/llms.txt"),
            "text/plain; charset=utf-8",
            POLICY,
        ),
        "/agent.json" => (
            include_str!("../../../web/landing/agent.json"),
            "application/json; charset=utf-8",
            POLICY,
        ),
        "/guide/zh-CN.md" => (
            include_str!("../../../web/landing/guide/zh-CN.md"),
            "text/markdown; charset=utf-8",
            POLICY,
        ),
        "/guide/ja.md" => (
            include_str!("../../../web/landing/guide/ja.md"),
            "text/markdown; charset=utf-8",
            POLICY,
        ),
        "/guide/en.md" => (
            include_str!("../../../web/landing/guide/en.md"),
            "text/markdown; charset=utf-8",
            POLICY,
        ),
        _ => return None,
    };
    Some(response(body, content_type, policy, staging))
}

/// Enforce one default security boundary; JSON-LD alone has a generated script hash.
fn response(body: &str, content_type: &str, policy: &str, staging: bool) -> Result<Response> {
    // Keep preview journeys on the paired workspace without changing discovery
    // metadata or the exact hashed JSON-LD bytes in the generated document.
    let staged_html = (staging && content_type.starts_with("text/html")).then(|| {
        body.replace(
            "href=\"https://skills.moesegfault.dev/",
            "href=\"https://skills-staging.moesegfault.dev/",
        )
    });
    let body = staged_html.as_deref().unwrap_or(body);
    let headers = Headers::new();
    headers.set("Content-Type", content_type)?;
    headers.set("Cache-Control", "public, max-age=300")?;
    headers.set("X-Content-Type-Options", "nosniff")?;
    headers.set("Referrer-Policy", "strict-origin-when-cross-origin")?;
    headers.set(
        "Permissions-Policy",
        "camera=(), microphone=(), geolocation=()",
    )?;
    headers.set("Content-Security-Policy", policy)?;
    if staging {
        headers.set("X-Robots-Tag", "noindex, nofollow")?;
    }
    Ok(Response::ok(body)?.with_headers(headers))
}

/// Executable code is same-origin only; no broad inline-script allowance is used.
const POLICY: &str = "default-src 'none'; script-src 'self'; style-src 'self'; img-src 'self'; connect-src 'self'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'";
